# Generated by Django 4.2.3 on 2023-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to='increment_image_name'),
        ),
    ]
