# Generated by Django 4.2.3 on 2023-07-15 11:49

import classification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_alter_plantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to=classification.models.increment_image_name),
        ),
    ]
