# Generated by Django 4.2.3 on 2023-07-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_plantimage_camera_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantimage',
            name='camera_source',
        ),
    ]
